# Generated by Django 3.1.1 on 2020-11-25 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('author', models.CharField(default='User', max_length=30)),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('views', models.IntegerField(default=0)),
                ('viewers', models.TextField(default='Z')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='dream',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='blog',
            name='blogauthor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tauthor', to='main.person'),
        ),
    ]
