# Generated by Django 3.1.1 on 2020-11-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201125_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='authorid',
            field=models.TextField(default='z'),
        ),
    ]
