# Generated by Django 3.1.1 on 2020-12-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blog_authorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dreamrubric',
            field=models.CharField(blank=True, choices=[('travel', 'Путешествия'), ('cars', 'Автомобили'), ('technology', 'Технологии'), ('meet', 'Встреча'), ('food', 'Еда'), ('sport', 'Спорт'), ('tourism', 'Туризм'), ('career', 'Карьера'), ('fashion', 'Мода'), ('collection', 'Коллекционирование'), ('health', 'Здоровье'), ('other', 'Другое')], max_length=100),
        ),
    ]
