# Generated by Django 3.1.1 on 2020-12-03 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201202_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dreamrubric',
            old_name='dreamrubric',
            new_name='drubric',
        ),
        migrations.AddField(
            model_name='biography',
            name='dream',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='biography',
            name='dreamrubric',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='biography',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.dreamrubric', verbose_name='Рубика'),
        ),
        migrations.AlterField(
            model_name='person',
            name='rubric',
            field=models.CharField(default='', max_length=100),
        ),
    ]
