# Generated by Django 3.1.1 on 2020-12-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201210_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='visited_profile',
            field=models.TextField(default='Z'),
        ),
    ]
