# Generated by Django 3.1.1 on 2020-12-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201211_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='subscribed',
            field=models.TextField(default='Z'),
        ),
    ]
