# Generated by Django 3.1.1 on 2020-12-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201211_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='stringid',
            field=models.TextField(default='Z'),
        ),
    ]
