# Generated by Django 3.1.1 on 2020-12-26 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=150)),
                ('comment_author', models.CharField(default='User', max_length=30)),
                ('comment_published', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('publicationcomment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.blog')),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
