# Generated by Django 3.1.1 on 2021-01-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201226_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_authorid',
            field=models.TextField(default='z'),
        ),
    ]
