# Generated by Django 3.1.5 on 2021-05-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210521_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='biography',
            field=models.CharField(default='Hello. I have not chosen my dream yet.', max_length=200),
        ),
    ]
